#!/usr/bin/env bash
CYGDIR=${HOME}/.cygwin
CYGBIN=${CYGDIR}/cygwin.exe

if [ ! -x $CYGBIN ]; then
	echo "Cygwin is not found or is not executable! Looking for ${CYGBIN}"
	exit 10
fi

install_pkg () {
	run_cygwin --download --packages $@
}

remove_pkg () {
	run_cygwin --remove-packages $@
}

pkg_opts () {
	if [ $(echo $@|head -c1) = "-" ]; then
		while getopts "y" opt; do
			case $opt in
				y)
					ATTENDANCE="--quiet-mode"
					;;
				-)
					break
					;;
				*)
					send_help
					exit 1
				
			esac
		done
	fi
}

prune_orphans () {
	run_cygwin --delete-orphans
}

windowsify_path () {
	cygpath --windows $@
}

run_cygwin () {
	echo "Launching Cygwin Setup..."
	$CYGBIN $COMMONARGS $ATTENDANCE $*|grep -v "Hand installation over to elevated child process."
}

send_help () {
	echo "Usage: $0 <install|remove|autoremove> [-y] [args]"
}

echoerr() {
	cat <<< "$@" 1>&2
	return
}

ATTENDANCE="--package-manager"
WIN_CYGROOT=$(windowsify_path /)
COMMONARGS="--wait \
	--no-shortcuts \
	--root "${WIN_CYGROOT}" \
	--local-package-dir "$(windowsify_path ${WIN_CYGROOT}${CYGDIR}/pkgsrc)" \
	--local-install "

subcmd=$1
shift
case $subcmd in
	install)
		pkg_opts $@
		if [ $OPTIND > 0 ]; then shift $(($OPTIND - 1)); fi
		install_pkg $@
		;;
	remove)
		pkg_opts $@
		if [ $OPTIND > 0 ]; then shift $(($OPTIND - 1)); fi
		remove_pkg $@
		;;
	autoremove)
		prune_orphans
		;;
	gui)
		unset COMMONARGS
		run_cygwin
		;;
	*)
		echo "Unknown subcommand: ${subcmd}"
		send_help
		exit 1
		;;
esac

